### ISSUE TITLE
Fails on Oracle Linux 7 due to 'with_items: "{{ ubuntu_packages }}"'

### ISSUE THREAD

**Issue by macdanny** [dj-wasabi/ansible-zabbix-web#10]
The issue is with the task to install php7 on Ubuntu systems. This task should be excluded on Oracle Linux systems which are RedHat based. But the task defines 'with_items: "{{ ubuntu_packages }}"', which ansible must be trying to resolve before it processes the when clause.

I'm pretty new to ansible and I'm not sure how to fix this. For my use case I just removed the task completely because we only use Oracle Linux at work.

Thanks for creating / maintaining these roles.

**Comment by dj-wasabi** [comment]
Hi @macdanny 

So, removing a task in `Debian.yml` helped you run the playbook on the Oracle Linux successfully? The `Debian.yml` should be completely ignored, as Oracle Linux is part of the RedHat family. I'll try to find a Oracle Linux docker container to see if I can replicate this behaviour.

**Comment by dj-wasabi** [comment]
Ah, the role is not using the `ansible_os_family` but the `ansible_distribution`. Seems this is common for all of my Zabbix roles. Will fix it.

**Comment by dj-wasabi** [comment]
As this one is solved a while ago in a pr, will close this.
