### ISSUE TITLE
Problem with first install in Debian 9x

### ISSUE THREAD

**Issue by nidr0x** [dj-wasabi/ansible-zabbix-web#20]
Hi @dj-wasabi,

I'm experiencing some troubles when i install over Debian 9x. The first try stops with this error:

> MODULE FAILURE
> 
> An exception occurred during task execution. To see the full traceback, use -vvv. The error was: apt.cache.FetchFailedException: W:GPG error: http://repo.zabbix.com/zabbix/3.4/debian stretch InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 082AB56BA14FE591, E:The repository 'http://repo.zabbix.com/zabbix/3.4/debian stretch InRelease' is not signed.
> failed: [35.227.67.118] (item=deb) => {
>     "changed": false, 
>     "item": "deb", 
>     "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_ukaNXF/ansible_module_apt_repository.py\", line 556, in <module>\n    main()\n  File \"/tmp/ansible_ukaNXF/ansible_module_apt_repository.py\", line 544, in main\n    cache.update()\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 464, in update\n    raise FetchFailedException(e)\napt.cache.FetchFailedException: W:GPG error: http://repo.zabbix.com/zabbix/3.4/debian stretch InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 082AB56BA14FE591, E:The repository 'http://repo.zabbix.com/zabbix/3.4/debian stretch InRelease' is not signed.\n", 
>     "module_stdout": "", 
>     "rc": 1
> }

If i try a second time, does not stop at this step, but when you are doing operations with APT over shell shows the same warning.

So, my fix for this problem are the next:

> - name: "Debian | Install gpg key"
>   apt_key:
>     keyserver: keyserver.ubuntu.com
>     id: 082AB56BA14FE591
>     state: present
>   when:
>     - zabbix_repo == "zabbix"
>   tags:
>     - zabbix-server
>     - init
>     - config
> 
> - name: "Debian | Installing repository {{ ansible_distribution }}"
>   apt_repository:
>     repo: "{{ item }} http://repo.zabbix.com/zabbix/{{ zabbix_version }}/{{ ansible_distribution.lower() }}/ {{ ansible_distribution_release }} main"
>     state: present
>   when:
>     - zabbix_repo == "zabbix"
>   with_items:
>     - deb-src
>     - deb
>   tags:
>     - zabbix-server
>     - init
>     - config

As you can see, i removed the sign keys from Zabbix and replaced with the Ubuntu keyserver and now i can run the first run without any errors.

Do you suggest another workaround for this problem?

**Comment by dj-wasabi** [comment]
Hi @nidr0x 

With the zabbix-agent role, I have a `vars/zabbix.yml` file that contains all keys. Maybe I should use that as well with the server and web roles. But first I need to find a proper Debian Stretch Docker image, so I can test this.

**Comment by nidr0x** [comment]
Hi @dj-wasabi 

Thank you so much for the fix.
