### ISSUE TITLE
update readme to include correct examples

### ISSUE THREAD

**Issue by ericsysmin** [dj-wasabi/ansible-zabbix-web#32]
**Describe the bug**
Role examples are incorrect and do not match role parameters

**Installation method/version**
* Ansible Galaxy / 1.1.0

**Comment by Arffeh** [comment]
Agreed, I ended up cludging the following to get through the variable roulette for all the zabbix-related packages:

database_type: mysql, zabbix_server_database: mysql, database_type_long: mysql, zabbix_server_database_long: mysql

**Comment by dj-wasabi** [comment]
It will be fixed with #37

**Comment by dj-wasabi** [comment]
I pushed 1.3.0 to the Galaxy this morning that contains the documentation fixes.
