### ISSUE TITLE
Problem Getting Apache Version

### ISSUE THREAD

**Issue by fxfitz** [dj-wasabi/ansible-zabbix-web#4]
So, I'm running Apache 2.4 (installed only using zabbix-server/zabbix-web roles, on `master` branch). But for some reason, when my vhost template gets set, it doesn't think it's actually running 2.4, because it has `Allow from all` instead of `Require all granted`.

```
# apachectl -v | grep 'version' | awk -F '/' '{ print $2 }'| awk '{ print $1 }' | cut -c 1-3
2.4
```

```
TASK [dj-wasabi.zabbix-web : Get Apache version] **********************************************************************************************************************************************************************
ok: [lab-zabbix.rogue] => {"changed": false, "cmd": "apachectl -v | grep 'version' | awk -F '/' '{ print $2 }'| awk '{ print $1 }' | cut -c 1-3", "delta": "0:00:00.009662", "end": "2017-08-28 20:18:15.502167", "rc": 0, "start": "2017-08-28 20:18:15.492505", "stderr": "/bin/sh: apachectl: command not found", "stderr_lines": ["/bin/sh: apachectl: command not found"], "stdout": "", "stdout_lines": []}
```

**Comment by fxfitz** [comment]
I have no idea why the `Get Apache version` task is saying it can't find apachectl, because as you can see, I ran it just fine.

**Comment by dj-wasabi** [comment]
Do you have `become: True` in your playbook? Maybe path issue normal user vs root user?

**Comment by dj-wasabi** [comment]
I close this issue, if this issue still appears please reopen it.
