### ISSUE TITLE
Make Apache optional but keep as default

### ISSUE THREAD

**Issue by kr4ut** [dj-wasabi/ansible-zabbix-web#58]
@dj-wasabi We like your work here and want to contribute :+1: Instead of ending up like so often writing an own one we rather like to enrich this role. First we like to make the Apache usage optional for getting internally rid of it's role dependency but keep it as default for compatibility. Will send you the PR later ...

**Comment by hatifnatt** [comment]
@kr4ut can you please describe how exactly dependency for `geerlingguy.apache` can be skipped? I can't get it to work. If I don't have `geerlingguy.apache` installed I've got error.
```
ERROR! the role 'geerlingguy.apache' was not found in ~/ansible/roles
The error appears to be in '~/roles/ansible-zabbix-web/meta/main.yml': line 29, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

dependencies:
  - name: geerlingguy.apache
    ^ here
```
Variables applied to host is very simple
```
zabbix_version: 4.2
zabbix_web_package_state: present
zabbix_url: tld.here
zabbix_websrv: none
```

Although if `geerlingguy.apache` installed all apache steps is correctly skipped during playbook execution.
Am I right and dependency must be installed anyway, but it is not executed when condition is not satisfied?

**Comment by kr4ut** [comment]
@hatifnatt Sorry for the late reference but it's `zabbix_websrv != apache` like documented here https://github.com/dj-wasabi/ansible-zabbix-web#dependencies
