### ISSUE TITLE
zabbix 4.4 is not supported

### ISSUE THREAD

**Issue by miettal** [dj-wasabi/ansible-zabbix-web#70]
**Is your feature request related to a problem? Please describe.**

yes. I updated zabbix-server version 4.2 -> 4.4, but dj-wasabi/ansible-zabbix-web did not yet support 4.4.

**Describe the solution you'd like**

dj-wasabi/ansible-zabbix-{server, agent, proxy}  already supported 4.4.
is dj-wasabi/ansible-zabbix-web plannning to support zabbix 4.4?

**Comment by miettal** [comment]
In my understanding, zabbix 4.4 supporting process just adds an entry to sign_keys.
do you have any technical problems?

**Comment by dj-wasabi** [comment]
Hi, haven't had any time yet. Will try to find some time this week to update the zabbix-web to work with 4.4.

**Comment by miettal** [comment]
thank you!

**Comment by dj-wasabi** [comment]
Just merged support for Zabbix 4.4. Will try to create a release today so it also available in the Galaxy.
